Removed CHUNK_SIZE template param in ChunkArray, ChunkStack,...
cgogn/CGoGN_2 pull request #255
Opened 2016-10-19 15:11 UTC by etienneschmitt

2016-10-19 15:14 UTC, etienneschmitt commented
J'ai aussi modifié le comportement de la fonction add_attribute pour qu'elle renvoie un attribut valide si on rajoute deux fois le même attribut (même type, même orbite, même nom). C'est plus pratique que de rajouter une méthode check_attribute à la cgogn1 (je trouve).

2016-10-19 15:18 UTC, sylvainthery commented
As-tu discuté avec Pierre de cette modif ?
Car hier j'étais avec lui quand il a fait la PR et on était d'accord
pour laisser le param template CHUNK_SIZE sur les Chunkarray, ChunkStack,..

2016-10-19 15:19 UTC, etienneschmitt commented
Ah non j'en ai pas parlé, je trouvais que ça allait de soi. Quel est l'intérêt de conserver ce param template ?

2016-10-19 15:22 UTC, sylvainthery commented
Rien n’empêche d'utiliser les containers en dehors des cartes,  et pourquoi se
priver de la souplesse du param CHUNK_SIZE ?

2016-10-19 15:22 UTC, etienneschmitt commented
Je veux dire on fixe en dur la valeur du CHUNK_SIZE dans un fichier. à partir de cet instant ça ne sert plus à rien de laisser des paramètres templates superflus (ils vaudront forcément CGOGN_CHUNK_SIZE !).

2016-10-19 15:24 UTC, etienneschmitt commented
Parce que (dans cgogn) on ne les utilise nulle part en dehors des cartes ?

2016-10-19 15:24 UTC, sylvainthery commented
Pour le moment ;)

2016-10-19 15:26 UTC, etienneschmitt commented
Oui mais même si on les utilisait en dehors leur CHUNK_SIZE devrait être le même que celui utilisé dans les cartes, non...?

2016-10-19 15:26 UTC, sylvainthery commented
pas forcément.

2016-10-19 15:30 UTC, etienneschmitt commented
Peux-tu développer stp ?

2016-10-19 15:37 UTC, pierrekraemer commented
Ca n'a aucun sens. Les ChunkArray et autres ChunkArrayContainer sont des classes utilitaires. Elles n'ont rien à voir avec des cartes ou les choix qui sont faits pour les cartes.
C'est comme si les développeurs des std::vector avaient fixé en dur le type des éléments parce qu'ils ne les utilisaient que avec un certain type.

2016-10-19 15:37 UTC, sylvainthery commented
Si j'ai envie d'utiliser un ChunkArrayContainer pour stocker des données qui n'on rien à voir avec les
cartes, pourquoi ne pas me laisser le choix du CHUNK_SIZE.
A cette endroit le paramètre ne gêne personne. Le pb c'était qu'il se propageait partout, dans
les cartes, les attributs, les algo d'import...

2016-10-19 15:54 UTC, etienneschmitt commented
Mais où en dehors des cartes avez-vous trouvé une utilité à ChunkArray ? Tel quel ils sont d'horribles containers. Pour commencer, soit leur taille est un multiple de CHUNK_SIZE, soit il faut trouver un moyen de savoir où sont les trous. En gros pas de ChunkArray sans structure de type ChunkArrayContainer pour les parcourir. Ça rend la comparaison aux génériques std::vector moyennement pertinente.
Après effectivement on peut se dire que quelqu'un pourrait un jour avoir l'envie de les stocker ses données en utilisant un ChunkArrayContainer (en supposant que cette personne ait envie de se tapper tous les défauts liés au passé de ces structures : nommer chaque ChunkArray avec un std::string (le nom de l'attribut pour la carte) etc.
Je trouve qu'on devrait retravailler complètement ces classes si l'objectif est d'offrir un minimum de généricité. Peut-être est-ce au programme ?

2016-10-19 16:26 UTC, pierrekraemer commented
Disons que fixer en dur la taille des chunks n'est pas dans l'esprit de ces classes.
Maintenant, il est fort probable que ces classes ne seront utilisées que dans cgogn, et que au sein de cgogn, il est fort probable qu'elles ne seront utilisées que pour contenir les attributs des orbites. Donc, comme la taille des chunks est fixée en dur au niveau de MapBaseData, on peut douter de la pertinence d'une telle paramétrisation de ces classes.
Mais, l'existence de ce paramètre n'est visible absolument nulle part d'autre que là où elles sont instanciées, à savoir dans MapBaseData. Partout ailleurs, il est fait usage des définitions de type déclarées au sein de MapBaseData. Ce paramètre ne se propage donc nulle part et ne gêne absolument pas le développement de tout le code qui touche aux cartes.
Est-il alors nécessaire de supprimer ce paramètre ? Non.
Maintenant, à la question "Est-il nécessaire de conserver ce paramètre ?", je réponds aussi non.
Mon avis s'est donc forgé sur le choix qui nécessitait le moins d'effort, à savoir conserver le paramètre en l'état.

2016-10-19 16:41 UTC, etienneschmitt commented
En dehors d'une simplification du code il n'y a pas un grand intérêt (mais c'est déjà bien). Je laisse cette PR pour valider le comportement d'add_attribute qui a légèrement été modifié. En espérant ne pas soulever un nouveau tollé !

2016-10-19 16:53 UTC, pierrekraemer commented
A vrai dire, je n'étais pas fan non plus du changement de comportement de add_attribute... (mais je ne voulais pas attaquer tous les fronts en même temps).
J'aime bien le fait que quand on demande l'ajout d'un attribut, cela échoue si l'action demandée (à savoir un ajout) n'a pas été fait. Cela me semble sémantiquement plus cohérent.
Comment fait-on pour s'assurer qu'un nouvel attribut a bien été créé, et que l'on ne récupère pas un attribut existant, si c'était ce que l'on voulait faire ?

2016-10-19 16:54 UTC, pierrekraemer commented on cgogn/core/cmap/cmap1.h
> +	using Attribute = Attribute<T, ORBIT>;
Il est nécessaire où ce typedef ?
Etant donné que le type Attribute ne dépend absolument plus du type de carte, j'avais enlevé ce typedef de toutes les classes de carte.

2016-10-19 17:02 UTC, etienneschmitt commented
Bon et bien demain je mettrai une nouvelle fonction check_attribute alors. Et oui j'avais besoin du typedef dans mes nouveaux tests.

Le 19 octobre 2016 18:53:24 GMT+02:00, Pierre Kraemer <notifications@github.com> a écrit :
>A vrai dire, je n'étais pas fan non plus du changement de comportement
>de add_attribute... (mais je ne voulais pas attaquer tous les fronts en
>même temps).
>J'aime bien le fait que quand on demande l'ajout d'un attribut, cela
>échoue si l'action demandée (à savoir un ajout) n'a pas été fait. Cela
>me semble sémantiquement plus cohérent.
>Comment fait-on pour s'assurer qu'un nouvel attribut a bien été créé,
>et que l'on ne récupère pas un attribut existant, si c'était ce que
>l'on voulait faire ?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/cgogn/CGoGN_2/pull/255#issuecomment-254873529

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

2016-10-19 17:45 UTC, pierrekraemer commented
Concernant le typedef Attribute, tu ne peux pas résoudre ton problème avec un include de attribute.h ? Parce que ce typedef semble vraiment ne servir à rien, il ne dépend en rien du contexte et il ne fixe pas un seul paramètre template.

2016-10-20 08:22 UTC, pierrekraemer commented
Est-ce qu'une éventuelle fonction `check_attribute` pourrait avoir un nom plus explicite par rapport à ce qu'elle fait du genre `add_or_get_attribute` ?

2016-10-20 08:33 UTC, sylvainthery commented
Et pourquoi pas utiliser la nouvelle version qui prend une ref sur l'attribut et lui ajouter un 
code de retour ADDED / GOT / FAILED ?

2016-10-20 08:34 UTC, untereiner commented
pourquoi juste ne pas laisser comme c'était et éviter de complexifier quelque chose que ne l'était pas

2016-10-20 09:39 UTC, pierrekraemer commented
Pour moi une interface claire de manipulation des attributs devrait être la suivante :

 - has_attribute<T, ORBIT>(name) : renvoie vrai si il existe un attribut de type T pour l'orbite ORBIT portant le nom donné, faux sinon.
 - has_attribute<T>(orbit, name) : similaire à la précédente.
 - has_attribute<ORBIT>(name) : renvoie vrai si il existe un attribut pour l'orbite ORBIT portant le nom donné (quel qu'en soit le type), faux sinon.
 - has_attribute(name, orbit) : similaire à la précédente.

 - add_attribute<T, ORBIT>(name) : crée un nouvel attribut de type T pour l'orbite ORBIT portant le nom donné et renvoie un handler pointant sur cet attribut. Renvoie un handler invalide si il existe déjà un attribut portant ce nom pour cette orbite (quel qu'en soit le type).

 - get_attribute<T, ORBIT>(name) : renvoie un handler pointant sur l'attribut de type T pour l'orbite ORBIT portant le nom donné. Renvoie un handler invalide si il n'existe pas un tel attribut.
 - get_attribute<T>(orbit, name) : similaire à la précédente.
 
 - remove_attribute(Attribute<T, ORBIT>) : supprime l'attribut correspondant au handler donné.
 - remove_attribute(orbit, name) : supprime l'attribut portant le nom donné pour l'orbite donnée (quel qu'en soit le type).

Tout le reste peut (doit ?) être supprimé.

2016-10-20 09:43 UTC, etienneschmitt commented
Dans l'ensemble pourquoi pas mais attention avec has_attribute : on ne peut pas avoir deux attributs de type T et U sur la même orbite avec le même nom. J'écrirais donc une seule fonction qui prend l'orbite et le nom mais qui se fiche du type.

2016-10-20 09:45 UTC, pierrekraemer commented
Tout à fait d'accord, d'autant plus que l'autre cas est couvert en regardant la validité du handler retourné par `get_attribute`.

2016-10-20 09:50 UTC, pierrekraemer commented
En même temps, c'est clair dans ce qui est exprimé :
 - la première version de `has_attribute` demande si il existe un attribut pour une certaine orbite ayant un certain type et portant le nom donné.
 - la deuxième version demande si il existe un attribut pour une certaine orbite portant le nom donné.
La question n'étant pas la même, il est normal que la réponse puisse ne pas être la même.
Maintenant, comme je viens de le dire, la première version est couverte en regardant si le handler retourné par un appel à `get_attribute` est valide. Mais si on ne voulait que savoir si il existait et pas obtenir de handler, le `has_attribute` est légèrement plus léger (mais je ne vois pas vraiment de use case).

2016-10-20 09:54 UTC, pierrekraemer commented on cgogn/core/tests/cmap/mapbase_test.cpp
> +	using Attribute = typename Map::template Attribute<T,ORBIT>;
Ce typedef est inutile. Il suffit d'inclure attribute.h et d'utiliser directement la classe `Attribute<T, ORBIT>`.

2016-10-20 09:54 UTC, etienneschmitt commented
oui tous les typedefs inutils sont virés. Il faut juste que je commite.

2016-10-20 13:45 UTC, untereiner requested changes
everyone has to agree before the changes are approved

2016-10-20 13:59 UTC, pierrekraemer commented
Pour reprendre la discussion ici, voilà l'interface de manipulation des attributs proposée :

 - `has_attribute<T, ORBIT>(name)` : renvoie vrai si il existe un attribut de type T pour l'orbite ORBIT portant le nom donné, faux sinon.
 - `has_attribute<T>(orbit, name)` : similaire à la précédente.
 - `has_attribute<ORBIT>(name)` : renvoie vrai si il existe un attribut pour l'orbite ORBIT portant le nom donné (quel qu'en soit le type), faux sinon.
 - `has_attribute(orbit, name)` : similaire à la précédente.

===

 - `get_attribute<T, ORBIT>(name)` : renvoie un handler pointant sur l'attribut de type T pour l'orbite ORBIT portant le nom donné. Si un tel attribut n'existe pas, il est créé.
 - `get_attribute<T>(orbit, name)` : similaire à la précédente.
 
===

 - `remove_attribute(Attribute<T, ORBIT>)` : supprime l'attribut correspondant au handler donné.
 - `remove_attribute(orbit, name)` : supprime l'attribut portant le nom donné pour l'orbite donnée (quel qu'en soit le type).

===

Avec la solution précédente :
 - si on veut s'assurer que l'attribut demandé existait déjà : on fait `get_attribute`puis si le handler récupéré est valide, alors on l'utilise
 - si on veut s'assurer que l'attribut n'existait pas (et qu'il va donc être créé) : on fait `add_attribute` puis si le handler récupéré est valide, alors on l'utilise
 - si on s'en fiche, on fait `get_attribute`, puis si le handler récupéré est valide, on l'utilise, sinon on fait appel à `add_attribute`

Avec cette solution :
 - si on veut s'assurer que l'attribut demandé existait déjà : on fait `has_attribute` puis dans le cas d'une réponse positive, on fait `get_attribute`.
 - si on veut s'assurer que l'attribut n'existait pas (et qu'il va donc être créé) : on fait `has_attribute` puis dans le cas d'une réponse négative, on fait `get_attribute`.
 - si on s'en fiche, on fait simplement `get_attribute`.

On voit que avec la nouvelle solution, il y a moins de méthodes différentes, et le cas où on s'en fiche est simplifié.

2016-10-20 14:06 UTC, sylvainthery commented
Éternelle discussion, mais  est-ce vraiment clair de faire get_attribute pour ajouter un attribut ?
Je crains que ça ne nuise à la lisibilité du code.
Pourquoi ne pas faire un add qui add et un get qui get ?

2016-10-20 14:07 UTC, pierrekraemer commented on cgogn/core/cmap/map_base.h
> +		cgogn_message_assert(orbit < NB_ORBITS, "Unknown orbit parameter");
Attention, dans les deux version de has_attribute, il faut ajouter la vérification du fait que l'orbite concernée est bien plongée (`is_embedded`). Sinon, il faut renvoyer faux.

2016-10-20 14:10 UTC, pierrekraemer commented
Pour moi, cette interface a quand même le gros avantage que `get_attribute` renvoie toujours un handler valide alors qu'avant on avait 2 méthodes `get_attribute` et `add_attribute` qui pouvaient l'une comme l'autre renvoyer un handler invalide alors que personne ne testait jamais la validité des handlers !!
Si on veut s'assurer de la pré-existence ou non d'un attribut, on `has_attribute` à disposition. Mais dans l'écrasante majorité des cas, on s'en fiche et c'est justement le cas qui est simplifié par la nouvelle interface proposée.

2016-10-20 14:11 UTC, pierrekraemer commented
On peut voir les choses comme le fait que `get_attribute` est une méthode qui get un attribute _handler_. Et c'est justement ce que fait la nouvelle version proposée. Dans tous les cas.

2016-10-20 14:16 UTC, sylvainthery commented
ça change rien au fait que quand tu lit du code, tu ne t'attends pas à ce que get fasse un ajout.
Peut-être un autre nom: ask ou ask_for me semblerait moins perturbant que get

2016-10-20 14:17 UTC, etienneschmitt commented
oui je trouve la proposition de Sylvain pertinente, ça lèverait pas mal de doutes quant au comportement de la fonction.

2016-10-20 14:21 UTC, pierrekraemer commented
Encore une fois, le **_get_** de `get_attribute` concerne le **_handler_** que l'on cherche à récupérer.
Si il a fallu créer un ChunkArray pour renvoyer un handler valide, ça ne me semble pas problématique.
Si ça semble un problème c'est uniquement à cause de nos habitudes.
Si nécessaire, on peut renommer au passage la méthode en `get_attribute_handler` (c'est pas une vraie proposition en fait..).

2016-10-20 14:43 UTC, pierrekraemer commented on cgogn/core/cmap/map_base.h
> +		cgogn_message_assert(orbit < NB_ORBITS, "Unknown orbit parameter");
D'ailleurs, est-ce qu'on n'écrit pas les 2 versions mais avec ORBIT en paramètre template ?
Dans les cas où on est dans un contexte où l'orbite est template, ça me semble plus naturel d'appeler également cette méthode en fixant l'orbite en tant que paramètre template (de la même manière que l'on a `is_embedded` en versions paramètre dynamique ou template).

2016-10-20 14:53 UTC, pierrekraemer commented
D'ailleurs on avait supprimé tous les "get" des noms des accesseurs. Si la méthode s'appelait simplement "attribute", ça ne résoudrait pas un peu les questions ? C'est un peu comme si on disait à la carte : "fais péter l'attribute handler" !
D'ailleurs, pour la gestion des buffers, on a une méthode `buffer` qui retourne un buffer existant si il en reste un disponible, ou en crée un nouveau si nécessaire..

2016-10-20 15:03 UTC, etienneschmitt commented
Moi sur la simplification de l'interface je suis 100% d'accord. Concernant le nommage je n'ai pas d'avis tranché. Supprimer let get_ me semble être cohérent avec ce qu'on a fait ailleurs. Je peux rapidement m'y attaquer (si ça convient à tout le monde).

2016-10-20 15:11 UTC, pierrekraemer commented
La principale raison pour laquelle on avait conservé le "get_" est parce qu'il y avait le "add_" à côté (de la même manière, il y a encore get_chunk_array et add_chunk_array dans le ChunkArrayContainer). Si il n'y a plus de "add_", on peut peut-être finir avec un triplet : `has_attribute` (qui renvoie vrai ou faux), `attribute` (qui renvoie un handler valide), `remove_attribute` (qui supprime un attribut) ?

2016-10-20 15:29 UTC, pierrekraemer commented
Est-ce qu'on arrivera encore à trancher aujourd'hui ?

2016-10-20 15:41 UTC, etienneschmitt commented
Ça dépend surtout de @untereiner  et de @sylvainthery ? Au niveau de la PR en dehors d'éventuelles demandes de modification je ne rajouterai rien.

2016-10-20 15:44 UTC, sylvainthery commented
J'avoue je reste perplexe face à la simplification à outrance des noms de fonction,
perso j'ai l'habitude (bonne ou mauvaise) de faire des ctrl-shift-f, avec des noms
comme ça c'est mort.
Mais si tout le monde est d'accord je m'incline.

2016-10-20 15:58 UTC, pierrekraemer commented
Dans la recherche de Qt Creator on peut utiliser des regexp si on veut faire des choses fines !

2016-10-20 16:11 UTC, david-cazier commented
Le comportement indiqué me convient que moyennement.
Je préfère avoir les get_attribute() et add_attribute() séparés.
Avec le add_ renvoyant une erreur si l'attibut existe déjà.
Le has_ peut être ajouté, si vous en voyez le besoin, mais reste facultatif.

J'ai été confronté à des cas où l'erreur du add_ m'a fait prendre conscience d'un problème (des appels récursifs à un algo ajoutant un plongement). Sans cette erreur rien n'aurait fonctionné sans que je comprenne pourquoi. Là j'ai simplement ajouter un chiffre aux noms de mes attributs.

Concernant le nom, comme Sylvain, j'aime bien get_attribute().
Je trouve que savoir, avec le nom, que c'est un "getteur" c'est bien.

2016-10-20 17:03 UTC, pierrekraemer commented
Attention, `add_attribute` n'a jamais renvoyé une erreur, mais un handler invalide. Encore faut-il tester la validité du handler renvoyé ! Et c'est une chose que l'on ne voit pas beaucoup.. En fait le seul intérêt de ce handler invalide n'est pas de le tester, mais de faire planter l'appli quand on va chercher à l'utiliser !
L'impression que j'ai est que le cas d'utilisation le plus courant est celui du `get_or_add_attribute`. Mais ce nom est tellement illisible que l'on est finalement arrivé à une solution où c'est simplement la méthode `attribute` qui a ce comportement.
Les méthodes `has_attribute` permettent quant à elles de s'assurer, si besoin, de la récupération d'un attribut existant ou de la création d'un nouvel attribut.

Si on reste sur une solution à base de `add_attribute` et `get_attribute`, alors il faut supprimer les méthodes `has_attribute` qui ne servent plus à rien étant donné que l'existence ou non d'un attribut est donnée par la validité ou non du handler retourné par `get_attribute`.
A ce moment là, je ne suis pas vraiment pour l'ajout d'une méthode `get_or_add_attribute`. La personne voulant ce comportement fera plutôt :
```c++
VertexAttribute<int32> a = map.get_attribute("nom");
if (!a.is_valid())
  a = map.add_attribute("nom");
```

D'ailleurs même un `get_or_add_attribute` ne renvoie pas un handler valide dans tous les cas. Il reste le cas où on demande un attribut de type T portant un certain nom et où ce nom est déjà utilisé par un attribut de type U. Dans ce cas, on ne peut ni fournir un handler sur un attribut existant, ni en créer un nouveau portant le nom demandé. Si on voulait, on pourrait laisser cgogn trouver automatiquement un nom disponible en ajoutant un nombre en fin de nom..

2016-10-20 17:06 UTC, pierrekraemer commented
Au sujet des noms des getters, le préfixe "get" a été supprimé de la grande majorité d'entre eux il y a de ça quelques temps.
Une uniformisation des noms pencherait donc ici plutôt pour une suppression du "get_".

2016-10-20 17:15 UTC, untereiner commented
Comme Sylvain, je pense que laisser le préfixe get_ est confusant sur le comportement de la fonction.

2016-10-21 06:09 UTC, pierrekraemer commented
Bon, après reflexion, voilà mes conclusions.
Comme indiqué dans mon post précédent, et contrairement à ce que je pensais, une méthode `attribute` qui ferait un ajout en cas d'absence de l'attribut demandé ne peut pas _toujours_ renvoyer un handler valide. Il reste le cas où il existe déjà pour cette orbite un attribut d'un autre type portant le même nom. Du coup, pour être propre, on ne peut quand même pas se passer soit de vérifier l'état des lieux a priori à l'aide de `has_attribute`, soit de vérifier la validité du handler récupéré a posteriori. Ce qui était pour moi l'avantage principal de l'approche tombe à l'eau..

Du coup, comme on a dans tous les cas besoin de faire un test, on a d'une part une approche qui consiste à devoir d'abord faire un test pour savoir comment la méthode va se comporter (ajout ou récupération) :
```c++
// là on s'assure que l'attribut va bien être créé
if (!map.has_attribute<Vertex::ORBIT>("nom")
  a = map.attribute<int32, Vertex::ORBIT>("nom");

// là on s'assure que l'attribut existait déjà
if (map.has_attribute<int32, Vertex::ORBIT>("nom")
  a = map.attribute<int32, Vertex::ORBIT>("nom");

// si on n'a pas besoin de savoir si l'attribut vient d'être créé ou non,
// on doit quand même vérifier la validité (cas de l'attribut d'un autre type avec le même nom)
a = map.attribute<int32, Vertex::ORBIT>("nom");
if (a.is_valid()) { ... }
```
Et une autre approche qui consiste à faire une action puis à vérifier que l'action demandée a bien été effectuée :
```c++
a = map.add_attribute<int32, Vertex::ORBIT>("nom");
// là on s'assure que l'attribut a bien être créé
if (a.is_valid()) { ... }

a = map.get_attribute<int32, Vertex::ORBIT>("nom");
// là on s'assure que l'attribut existait déjà
if (a.is_valid()) { ... }
```
Finalement, je préfère la deuxième solution qui correspond à la situation actuelle. L'interface est donc exactement la première que j'avais détaillé plus haut dans cette discussion. Les méthodes `has_attribute` ne sont alors pas vraiment nécessaires, mais on peut les garder. Avec elles, si on ne veut vraiment que vérifier l'existence d'un attribut (et pas en obtenir un handler), on peut le faire sans avoir à construire un handler et à en vérifier la validité.

Bon, quels sont vos avis ?

2016-10-21 06:27 UTC, etienneschmitt commented
Je pense que l'avis général est qu'on va se tourner vers cette solution.
Par contre, la syntaxe que j'avais proposée il y a quelques temps (et rajoutée) j'en fais quoi (le fonctions qui modifient l'attribut par effet de bord)? J'ai l'impression que son utilité n'a pas convaincu grand monde et je pense donc virer les fonctions de ce type.
Ensuite il reste le cas de fonctions renvoyant des Attribute_T qui n'ont sans doute pas leur place ici mais plutôt dans les wrapper qui sont déjà dans SCHNapps ou Sofa. Je pense qu'elles peuvent dégager aussi.

2016-10-21 06:30 UTC, etienneschmitt commented
Concernant les méthodes has_attribute, celle permettant de savoir si la création d'un attribut va aboutir me semble sympa.
La deuxième version (qui prend le type en param template) correspond au cas où l'on fait un get_attribute et teste sa validité non ? Peut-être peut-on s'en passer.

2016-10-21 06:40 UTC, pierrekraemer commented
Concernant ma dernière piste de reflexion sur l'abandon de l'unicité du nom au profit de l'unicité du couple (type, nom), ça serait un peu pénible pour une interface comme SCHNApps où il faudrait en permanence gérer et afficher le couple plutôt que juste le nom.

Sinon oui je suis plutôt pour l'abandon des méthodes qui modifient un handler par effet de bord.
La version de `get_attribute` qui renvoie un Attribute_T n'est pas forcément gênante ici.

2016-10-21 07:16 UTC, closed without merging